# Generated by Django 4.2.7 on 2025-12-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgivenesscount',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='friendcomment',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
