# Generated by Django 4.2.7 on 2025-12-26 07:21

from django.db import migrations


def create_tables_manually(apps, schema_editor):
    """Manually create tables if they don't exist"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Create FriendComment table if it doesn't exist
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS special_friendcomment (
                id SERIAL PRIMARY KEY,
                text TEXT NOT NULL,
                timestamp TIMESTAMP WITH TIME ZONE,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
            );
        """)
        
        # Create ForgivenessCount table if it doesn't exist
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS special_forgivenesscount (
                id SERIAL PRIMARY KEY,
                count INTEGER NOT NULL DEFAULT 0,
                last_updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
            );
        """)


def reverse_create_tables(apps, schema_editor):
    """Drop tables if needed"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS special_friendcomment;")
        cursor.execute("DROP TABLE IF EXISTS special_forgivenesscount;")


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0002_alter_forgivenesscount_last_updated_and_more'),
    ]

    operations = [
        migrations.RunPython(create_tables_manually, reverse_create_tables),
    ]
