# Generated by Django 5.2.8 on 2025-12-24 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychartistApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='psychartist_profiles/')),
                ('specialization', models.CharField(max_length=200)),
                ('years_of_experience', models.IntegerField()),
                ('education', models.TextField()),
                ('certifications', models.TextField(blank=True)),
                ('approach', models.CharField(max_length=200)),
                ('languages', models.CharField(blank=True, max_length=200)),
                ('available_hours', models.CharField(blank=True, max_length=200)),
                ('session_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bio', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychartist_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Psychartist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='psychartist_profiles/')),
                ('specialization', models.CharField(max_length=200)),
                ('years_of_experience', models.IntegerField()),
                ('education', models.TextField()),
                ('certifications', models.TextField(blank=True)),
                ('approach', models.CharField(max_length=200)),
                ('languages', models.CharField(blank=True, max_length=200)),
                ('available_hours', models.CharField(blank=True, max_length=200)),
                ('session_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bio', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychartist_profile', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychartist_profile', to='psychartist.psychartistapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
