# Generated by Django 4.2.7 on 2025-12-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychartist', '0001_initial'),
    ]

    operations = [
    ]
